---

- hosts: all
  become: true
  pre_tasks:

  - name: Installing epel-release and dnf
    yum:
      name:
        - epel-release
        - yum
    when: ansible_distribution == "CentOS"

  - name: Update and upgrade remote CentOS server
    yum:
      update_cache: yes
      name:  "*"
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: kibana
  tags: kibana
  become: true
  roles:
    - { role: kibana, target_ip: 192.168.56.108, ip_host: 192.168.56.109, gpg_key_kibana: https://artifacts.elastic.co/GPG-KEY-elasticsearch }

- hosts: elasticsearch
  tags: es
  become: true
  roles:
    - { role: elasticsearch, ip_host: 192.168.56.109 }

- hosts: logstash
  tags: logstash
  become: true
  roles:
    - role: logstash
      gpg_key_logstash: https://artifacts.elastic.co/GPG-KEY-elasticsearch
